track_path = '/NOBACKUP/nii/typhoon_data/new_track/'
image_path = '/NOBACKUP/nii/typhoon_data/resize-image-cubic-interpolation-224-224/'
# image_path = '/NOBACKUP/nii/typhoon_data/orig_image/'
# image_path = '/NOBACKUP/nii/typhoon_data/224_224_crop_typhoon_image/'
# image_path = '/NOBACKUP/nii/typhoon_data/resize-image-cubic-interpolation-128-128/'
# image_path = '/NOBACKUP/nii/typhoon_data/resize-image-cubic-interpolation-224-224/'
# image_path = '/NOBACKUP/nii/typhoon_data/data_test/image'	
track_dic_path = '/NOBACKUP/nii/typhoon_data/new_track_dict.json'
# shuffled_id_path = '/NOBACKUP/nii/typhoon_data/id.json'
# suspicious_file_list_path = '/NOBACKUP/nii/typhoon_data/orig_suspected_file_list_resnet_1.0.json'
# suspicious_file_list_path = '/NOBACKUP/nii/typhoon_data/rev224_suspected_file_list.json'
# train_validation_test_subdirs_split = '/NOBACKUP/nii/typhoon_data/train_validation_test_subdirs_split_resnet_1.0.json'

# train_test_file_path_divid = '/NOBACKUP/nii/typhoon_data/orig_train_test_file_path_divid_vgg_19.json'
suspicious_file_list_path = '/NOBACKUP/nii/typhoon_data/orig_suspected_file_list.json'
# suspicious_file_list_path = '/NOBACKUP/nii/typhoon_data/rev224_suspected_file_list.json'
train_validation_test_subdirs_split = '/NOBACKUP/nii/typhoon_data/train_validation_test_subdirs_split_9.0.json'

train_test_file_path_divid = '/NOBACKUP/nii/typhoon_data/orig_train_test_file_path_divid_vgg_20_3.0_crop_rotate.json'
# train_test_file_path_divid = '/NOBACKUP/nii/typhoon_data/orig_train_test_file_path_divid_4.2.json'
# yType = 'tropicalornot'
num_labels = 12
yType ='type'
image_min_value = 113.21193
image_max_value = 340.7741416
mean_v = 269.57
std_v = 25.54
img_rows= 224
img_cols =224
look_back = 6
ModelCheckpoint_file = 'test_file/orig_weights_lstm_1.0_image_lookback_'+str(look_back)+'_whole_equal_pretrain_epoch_1000_adadelta_0.0001_zero_prediction_initial_normalization_type.hdf5'
#ModelCheckpoint_file='test_file/orig_weights_lstm_1.0_image_lookback_6_whole_equal_pretrain_epoch_1000_adadelta_0.0001.hdf5'
# ModelCheckpoint_file = 'test_file/orig_weights_lstm_1.0_image_lookback_6_whole_equal_pretrain_epoch_1000_adadelta_0.0001_zero_prediction.hdf5'
# ModelCheckpoint_file='test_file/orig_weights_lstm_1.0_image_lookback_12_whole_equal_pretrain_epoch_1000_adadelta_0.0001_prediction_zero.hdf5'
# ModelCheckpoint_file='test_file/orig_hist_lstm_1.0_image_lookback_12_whole_equal_pretrain__epoch_1000_adadelta_0.0001_prediction.hdf5'
# ModelCheckpoint_file='test_file/orig_weights_lstm_1.0_image_lookback_24_whole_equal_pretrain_epoch_1000_adadelta_0.0001_prediction_zero.hdf5'
# csv_path = 'test_file/orig_predict_4.2.csv'
# confusion_matrix_path = 'test_file/orig_cm_4.2.json'
# hist_path = 'test_file/orig_hist_4.2.json'
csv_path = 'test_file/orig_predict_lstm_1.0_image_lookback_'+str(look_back)+'_whole_equal_pretrain.csv'
confusion_matrix_path = 'test_file/orig_cm_lstm_1.0_image_lookback_'+str(look_back)+'_whole_equal_epoch_100.json'
hist_path = 'test_file/orig_hist_lstm_1.0_image_lookback_'+str(look_back)+'_whole_equal_pretrain_epoch_1000_adadelta_0.0001_zero_predictioninitial_normalization_type.json'
nb_epoch = 100
optimizer = 'sgd'
nb_worker =100
batch_size = 1
loss_image_path = 'test_file/loss_lstm_1.0_image_lookback_'+str(look_back)+'_whole_equal.jpg'
acc_image_path = 'test_file/acc_lstm_1.0_image_lookback_'+str(look_back)+'_whole_equal.jpg'
intensity_mean = 983.426
intensity_std = 22.5749
train_predict_image = 'test_file/train_predict_look_back_'+str(look_back)+'_look_back_image_whole_equal_pretrain_epoch_1000_adadelta_0.0001_prediction_zero_initial_method_2.png'
test_predict_image = 'test_file/test_predict_look_back_'+str(look_back)+'_look_back_image_whole_equal_pretrain_epoch_1000_adadelta_0.0001_prediction_zero_initial_method_2.png'
data_folder_path = 'test_file/train_test_folder_equal_pretrain.json'
data_path = 'test_file/train_test_data'+str(look_back)+'_zero_prediction.hdf5'
vgg_fc2_mean = 0.423964
vgg_fc2_std = 0.569374